// ============================================================
//  目录 —— role 语义角色 + 可绑定的 shadcn 组件
//  两者组合即「role + component」设计单元
// ============================================================

/** 语义角色建议列表（节点 role 字段） */
export const ROLES: string[] = [
  "page",
  "navigation",
  "header",
  "main",
  "content",
  "branding",
  "heading",
  "search",
  "actions",
  "action",
  "cta",
  "stats",
  "stat-card",
  "charts",
  "chart",
  "table",
  "data-table",
  "toolbar",
  "filters",
  "filter",
  "filter-tabs",
  "pagination",
  "caption",
  "user-profile",
  "form",
  "field",
  "list",
  "list-item",
  "card",
  "footer",
  "section",
  "sidebar",
  "hero",
  "feature",
  "testimonial",
]

/** 可绑定的 shadcn/ui 组件目录 */
export const COMPONENTS: string[] = [
  "Button",
  "Input",
  "Textarea",
  "Select",
  "Checkbox",
  "RadioGroup",
  "Switch",
  "Slider",
  "Card",
  "Badge",
  "Avatar",
  "Table",
  "Tabs",
  "Accordion",
  "Alert",
  "Dialog",
  "DropdownMenu",
  "Popover",
  "Tooltip",
  "Calendar",
  "Pagination",
  "Separator",
  "Skeleton",
  "Sidebar",
  "SidebarMenu",
  "Breadcrumb",
  "ChartContainer",
]
